// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtS8eWytZphnYyeOUm-5OSJlvw0B0n6f4',
    appId: '1:233316288461:web:a4a1e73f6396391cbae684',
    messagingSenderId: '233316288461',
    projectId: 'personal-portfolio-d68ab',
    authDomain: 'personal-portfolio-d68ab.firebaseapp.com',
    storageBucket: 'personal-portfolio-d68ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqgYztPIxNLLSaSenYSo0KJ4k45phTXqw',
    appId: '1:233316288461:android:2ae221dc2d7f720cbae684',
    messagingSenderId: '233316288461',
    projectId: 'personal-portfolio-d68ab',
    storageBucket: 'personal-portfolio-d68ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG3xSrq5pz99D6Wd_WUFzba3asx2Orgbc',
    appId: '1:233316288461:ios:5fdc608d9afdd5e4bae684',
    messagingSenderId: '233316288461',
    projectId: 'personal-portfolio-d68ab',
    storageBucket: 'personal-portfolio-d68ab.firebasestorage.app',
    iosBundleId: 'com.example.personalPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG3xSrq5pz99D6Wd_WUFzba3asx2Orgbc',
    appId: '1:233316288461:ios:5fdc608d9afdd5e4bae684',
    messagingSenderId: '233316288461',
    projectId: 'personal-portfolio-d68ab',
    storageBucket: 'personal-portfolio-d68ab.firebasestorage.app',
    iosBundleId: 'com.example.personalPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtS8eWytZphnYyeOUm-5OSJlvw0B0n6f4',
    appId: '1:233316288461:web:4c5139e9b308b4e5bae684',
    messagingSenderId: '233316288461',
    projectId: 'personal-portfolio-d68ab',
    authDomain: 'personal-portfolio-d68ab.firebaseapp.com',
    storageBucket: 'personal-portfolio-d68ab.firebasestorage.app',
  );
}
